# Generated by Django 2.2.1 on 2019-05-30 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
