# Generated by Django 2.2.1 on 2019-06-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
