# Generated by Django 2.2.1 on 2019-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_user_unique_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Role - 0: customer, 1: manager'),
        ),
    ]
